root: true
extends:
  - "eslint:recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:@typescript-eslint/recommended"
  - "eslint-config-prettier"
  - "plugin:import/recommended"
  - "../.eslintrc.yml"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "node_modules"
  - "lib"
