create extension if not exists pg_jsonschema
with
  schema public version '0.3.3';

create table public.push_subscriptions (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid (),
  created_at timestamp with time zone not null default now(),
  endpoint text not null,
  expiration_time double precision null,
  keys json not null
);

alter table public.push_subscriptions
add constraint push_subscriptions_pkey primary key (id);

alter table public.push_subscriptions
add constraint push_subscriptions_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade not valid;

alter table public.push_subscriptions
add constraint endpoint_is_url check (endpoint ~ '^https://[^/]+\.[a-z]+/');

alter table only public.push_subscriptions
add constraint unique_endpoint unique (endpoint);

alter table public.push_subscriptions
add constraint keys_json_schema check (
  json_matches_schema (
    '{
      "type": "object",
      "properties": {
        "p256dh": { "type": "string" },
        "auth": { "type": "string" }
      },
      "required": ["p256dh", "auth"],
      "additionalProperties": false
    }',
    keys
  )
);

alter table public.push_subscriptions enable row level security;

grant all on table public.push_subscriptions to anon;

grant all on table public.push_subscriptions to authenticated;

grant all on table public.push_subscriptions to service_role;

create policy allow_all_if_user_matches on public.push_subscriptions as permissive for all to authenticated using (
  (
    (
      select
        auth.uid ()
    ) = user_id
  )
)
with
  check (
    (
      (
        select
          auth.uid ()
      ) = user_id
    )
  );

create or replace function unsubscribe_from_push (endpoint_to_delete text) returns void language sql security definer as $$
  delete from public.push_subscriptions
  where
    endpoint = endpoint_to_delete;
$$;

create or replace function subscribe_to_push (
  endpoint text,
  expiration_time double precision,
  keys json
) returns void language sql as $$
  select
    unsubscribe_from_push (endpoint);

  insert into
    public.push_subscriptions (endpoint, expiration_time, keys)
  values
    (endpoint, expiration_time, keys);
$$;
