create extension if not exists pg_jsonschema
with
  schema public version '0.3.3';

create table public.push_subscriptions (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid (),
  subscription json not null,
  created_at timestamp with time zone not null default now()
);

alter table public.push_subscriptions
add constraint push_subscriptions_pkey primary key (id);

alter table public.push_subscriptions
add constraint push_subscriptions_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade not valid;

create unique index push_subscriptions_unique_subscription on public.push_subscriptions (user_id, (subscription::text));

alter table public.push_subscriptions
add constraint subscription_schema check (
  json_matches_schema (
    '{
      "type": "object",
      "properties": {
        "endpoint": { "type": "string", "format": "uri" },
        "expirationTime": { "type": ["number", "null"] },
        "keys": {
          "type": "object",
          "properties": {
            "p256dh": { "type": "string" },
            "auth": { "type": "string" }
          },
          "required": ["p256dh", "auth"],
          "additionalProperties": false
        }
      },
      "required": ["endpoint", "expirationTime", "keys"],
      "additionalProperties": false
    }',
    subscription
  )
);

alter table public.push_subscriptions enable row level security;

grant all on table public.push_subscriptions to anon;

grant all on table public.push_subscriptions to authenticated;

grant all on table public.push_subscriptions to service_role;

create policy allow_all_if_user_matches on public.push_subscriptions as permissive for all to authenticated using (
  (
    (
      select
        auth.uid ()
    ) = user_id
  )
)
with
  check (
    (
      (
        select
          auth.uid ()
      ) = user_id
    )
  );
