name: CI/CD

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  lint-vite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: lint
        run: npm run lint
        working-directory: ./client

  lint-functions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: ./functions

      - name: lint
        run: npm run lint
        working-directory: ./functions

  build-vite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Install dependencies in functions
        run: npm ci
        working-directory: ./functions

      - name: build
        run: npm run build:prod
        working-directory: ./client

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: ng-dist
          path: dist/Connexagon

  build-functions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: ./functions

      - name: build
        run: npm run build
        working-directory: ./functions

      - name: Upload lib
        uses: actions/upload-artifact@v2
        with:
          name: functions-lib
          path: functions/lib/

  deploy:
    runs-on: ubuntu-latest
    needs: [build-ng, build-functions]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies in functions
        run: npm ci
        working-directory: ./functions

      - name: Download ng-dist
        uses: actions/download-artifact@v2
        with:
          name: ng-dist
          path: dist/Connexagon

      - name: Download functions-lib
        uses: actions/download-artifact@v2
        with:
          name: functions-lib
          path: functions/lib/

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -m "${GITHUB_SHA}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
