name: Deploy to Production

on:
  push:
    branches:
      - next

permissions:
  contents: read

jobs:
  migration:
    name: Deploy Supabase Migrations
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: npx supabase db push
